### ISSUE TITLE
supportOAID()==false或onOAIDGetError()回调时，还有重试的必要吗？永远不可能了？

### ISSUE THREAD

**Issue by tigerose** [gzu-liyujiang/Android_CN_OAID#10]
比如下次启动app，对比这次获取失败时，可能连网状态不同，也可能安卓rom版本发生了变化，等等等等；
有没有可能这次不行，下次再次尝试又可以获取到oaid？

**Comment by liyujiang-gzu** [comment]
supportOAID()==false时没重试的必要了，error回调时重试也许可以。

**Comment by liyujiang-gzu** [comment]
由于异常情况我们没法预知，如果是**android10及以上版本**的系统，之前没获取到oaid的话，最好是在需要oaid时再尝试获取一下

**Comment by tigerose** [comment]
> 由于异常情况我们没法预知，如果是**android10及以上版本**的系统，之前没获取到oaid的话，最好是在需要oaid时再尝试获取一下

好的好的
