### ISSUE TITLE
请问BUN UODIS分别是什么手机系统？

### ISSUE THREAD

**Issue by feierlaiedu** [gzu-liyujiang/Android_CN_OAID#11]

**Comment by feierlaiedu** [comment]
ZTE中兴和华为是吧。。建议备注说明下

**Comment by liyujiang-gzu** [comment]
> ZTE中兴和华为是吧。。建议备注说明下

有些不仅仅是一个厂商，比如ZUI适用于联想和摩托罗拉

**Comment by feierlaiedu** [comment]
> > ZTE中兴和华为是吧。。建议备注说明下
> 
> 有些不仅仅是一个厂商，比如ZUI适用于联想和摩托罗拉

嗯，还是建议能注释说明下 都包括哪些品牌机型 有些机型用户量太小 可能就不考虑接入了
