### ISSUE TITLE
关于realme手机获取不到oaid 

### ISSUE THREAD

**Issue by zhangxiaojin770** [gzu-liyujiang/Android_CN_OAID#12]
这个项目有没有关于realme 手机获取oaid的

**Comment by liyujiang-gzu** [comment]
这个项目的OAID获取接口主要来自于北京数字联盟公开的代码并逆向分析参考移动安全联盟的SDK，酷派、乐视、真我、锤子等厂商目前（2021.01.19）并未见移动安全联盟有支持，也为查阅到相关资料，只能自行生成GUID了。

**Comment by liyujiang-gzu** [comment]
> 这个项目有没有关于realme 手机获取oaid的

这个项目的OAID获取接口主要来自于北京数字联盟公开的代码并逆向分析参考移动安全联盟的SDK，酷派、乐视、真我、锤子等厂商目前（2021.01.19）并未见移动安全联盟有支持，也为查阅到相关资料，只能自行生成GUID了。

**Comment by gonejack** [comment]
请问OAID的格式是厂商各自决定的吗？看预览图里那么多种格式。

**Comment by liyujiang-gzu** [comment]
> 请问OAID的格式是厂商各自决定的吗？看预览图里那么多种格式。

是的，OAID的格式是厂商各自决定的，统一格式的话，建议进行md5或sha1之类的哈希运算

**Comment by liyujiang-gzu** [comment]
@gonejack [真我手机据说是OPPO旗下子品牌](https://baijiahao.baidu.com/s?id=1641944540101270063)，当作OPPO手机处理，你用你的真我手机试一下看能不能获取到OAID？

**Comment by gonejack** [comment]
我手头没有 realme 手机了，realme 使用的系统是 OPPO 的 ColorOS，应是一致的。

**Comment by liyujiang-gzu** [comment]
> 我手头没有 realme 手机了，realme 使用的系统是 OPPO 的 ColorOS，应是一致的。

加了国内几大厂商的子品牌手机的支持：华为荣耀、小米红米、维沃爱酷、欧珀真我。
https://github.com/gzu-liyujiang/Android_CN_OAID/releases/download/3.0.3/app-release-resguard-3.0.3-20210414.apk

**Comment by s240875886** [comment]
@gonejack 不用一致，是肯定获取不到

**Comment by gonejack** [comment]
获取不到OAID还是IMEI？

**Comment by s240875886** [comment]
@gonejack OAID

**Comment by liyujiang-gzu** [comment]
> @gonejack OAID

要android 10+才支持

**Comment by liyujiang-gzu** [comment]
Realme当作OPPO机处理，已支持：  
![微信截图_20210429152223](https://user-images.githubusercontent.com/16816717/116524140-9f755a00-a909-11eb-91d0-c7a1b9aa7eaa.png)
