### ISSUE TITLE
关于华为，荣耀手机获取不到oaid

### ISSUE THREAD

**Issue by zhangxiaojin770** [gzu-liyujiang/Android_CN_OAID#14]
isSupport-->true----->oaid--->00000000-0000-0000-0000-000000000000
支持获取oaid 但是获取到oaid 都为0的字符串  最后查到是因为用户设置了“匿名识别标识”为关闭 有没有什么办法可以曲线救国保证拿到相关的oaid

**Comment by liyujiang-gzu** [comment]
> isSupport-->true----->oaid--->00000000-0000-0000-0000-000000000000
> 支持获取oaid 但是获取到oaid 都为0的字符串 最后查到是因为用户设置了“匿名识别标识”为关闭 有没有什么办法可以曲线救国保证拿到相关的oaid

这种情况下是拿不到OAID的，OAID的初衷就是为了保护用户隐私，用户不允许获取OAID华为当然会遵循用户意愿。

**Comment by zhangxiaojin770** [comment]
> > isSupport-->true----->oaid--->00000000-0000-0000-0000-000000000000
> > 支持获取oaid 但是获取到oaid 都为0的字符串 最后查到是因为用户设置了“匿名识别标识”为关闭 有没有什么办法可以曲线救国保证拿到相关的oaid
> 
> 这种情况下是拿不到OAID的，OAID的初衷就是为了保护用户隐私，用户不允许获取OAID华为当然会遵循用户意愿。

那就是拿不到的意思吗？ 这种情况客户端只能自己本地生成了吗？

**Comment by liyujiang-gzu** [comment]
> > > isSupport-->true----->oaid--->00000000-0000-0000-0000-000000000000
> > > 支持获取oaid 但是获取到oaid 都为0的字符串 最后查到是因为用户设置了“匿名识别标识”为关闭 有没有什么办法可以曲线救国保证拿到相关的oaid
> > 
> > 
> > 这种情况下是拿不到OAID的，OAID的初衷就是为了保护用户隐私，用户不允许获取OAID华为当然会遵循用户意愿。
> 
> 那就是拿不到的意思吗？ 这种情况客户端只能自己本地生成了吗？

是的，尊重用户隐私，用户不让拿，就只能自己本地搞一个GUID，只要用户不卸载APP就行。

**Comment by zhangxiaojin770** [comment]
> > > > isSupport-->true----->oaid--->00000000-0000-0000-0000-000000000000
> > > > 支持获取oaid 但是获取到oaid 都为0的字符串 最后查到是因为用户设置了“匿名识别标识”为关闭 有没有什么办法可以曲线救国保证拿到相关的oaid
> > > 
> > > 
> > > 这种情况下是拿不到OAID的，OAID的初衷就是为了保护用户隐私，用户不允许获取OAID华为当然会遵循用户意愿。
> > 
> > 
> > 那就是拿不到的意思吗？ 这种情况客户端只能自己本地生成了吗？
> 
> 是的，尊重用户隐私，用户不让拿，就只能自己本地搞一个GUID，只要用户不卸载APP就行。

那有点好奇 抖音在获取不到oaid的时候，如何获取到imei并且返回给我们的呢，有点奇怪，还有友盟也是

**Comment by liyujiang-gzu** [comment]
> > > > > isSupport-->true----->oaid--->00000000-0000-0000-0000-000000000000
> > > > > 支持获取oaid 但是获取到oaid 都为0的字符串 最后查到是因为用户设置了“匿名识别标识”为关闭 有没有什么办法可以曲线救国保证拿到相关的oaid
> > > > 
> > > > 
> > > > 这种情况下是拿不到OAID的，OAID的初衷就是为了保护用户隐私，用户不允许获取OAID华为当然会遵循用户意愿。
> > > 
> > > 
> > > 那就是拿不到的意思吗？ 这种情况客户端只能自己本地生成了吗？
> > 
> > 
> > 是的，尊重用户隐私，用户不让拿，就只能自己本地搞一个GUID，只要用户不卸载APP就行。
> 
> 那有点好奇 抖音在获取不到oaid的时候，如何获取到imei并且返回给我们的呢，有点奇怪，还有友盟也是 并且在用户没有权限的情况下 可以获取到

友盟在用户没有权限的情况下获取到的IMEI肯定是假的，原理应该是差不多的，本地生成或服务端生成GUID存到外部存储卡的公共区域，在Android10以下就算用户卸载了APP，任然可以从外部存储卡取出来，但是Android11+读写公共区域需要`MANAGE_EXTERNAL_STORAGE`权限。比如极光推送的`RegistrationID`的生成规则（[极光推送的设备唯一性标识 RegistrationID](https://community.jiguang.cn/article/38100)）基本上就是如此。
