### ISSUE TITLE
GUID 两次获取不一致

### ISSUE THREAD

**Issue by Yanqilong** [gzu-liyujiang/Android_CN_OAID#16]
机器： HUAWEIP30
SDK： SDK 29 Android 10系统
两次安装demo，分别获取的 GUID 不一致，算是一个 bug 吗？

**Comment by liyujiang-gzu** [comment]
guid是在首次使用时随机生成存在本地的，app卸载后保存的guid就丢失了，再次安装使用自然会重新生成

**Comment by Yanqilong** [comment]
我理解错了，谢谢
