### ISSUE TITLE
当前项目跟官方的有什么区别

### ISSUE THREAD

**Issue by lgengsy** [gzu-liyujiang/Android_CN_OAID#17]
已经有了一官方的项目，当前项目跟官方的有什么差异，获取到的OAID 会不会不一致。

**Comment by lgengsy** [comment]
另外，我看到友盟也集成了OAID并且对外暴露了获取OAID的方法。

**Comment by lgengsy** [comment]
vvid， aaid获取的方法有没有？？

**Comment by liyujiang-gzu** [comment]
> 已经有了一官方的项目，当前项目跟官方的有什么差异，获取到的OAID 会不会不一致。

和移动安全联盟官方的SDK是一样的功能，都是基于各大手机厂商的提供的接口进行封装。本方案和官方的实现方式不一样，源代码掌控在自己手里。，官方的SDK加固封闭，下载SDK都需要取注册并提供企业信息，对大部分开发者来说是很不友好的吗，也不利于技术的推进和团体标准的谱及。
