### ISSUE TITLE
motorola edge 国内不支持

### ISSUE THREAD

**Issue by nodephp** [gzu-liyujiang/Android_CN_OAID#24]
motorola edge s  国内版本 会提示 Google Play services not available 实际已经获取到oaid

**Comment by liyujiang-gzu** [comment]
> motorola edge s 国内版本 会提示 Google Play services not available 实际已经获取到oaid

出现这个提示是因为没有安装谷歌应用商店，`Google Play Service SDK` 代码里有检查 `com.android.vending`，即：
```groovy
      PackageInfo pi = context.getPackageManager().getPackageInfo("com.android.vending", 0);
      return pi != null;
```

**Comment by liyujiang-gzu** [comment]
> 实际已经获取到oaid

`实际已经获取到oaid`这个是你是怎么知道的？摩托罗拉手机会依次进行如下尝试以判断：
```
LenovoImpl
MsaImpl
GmsImpl
DefaultImpl
```

**Comment by nodephp** [comment]
OAIDLog.print("Get uuid from preferences: " + uuid); 这边后输出

**Comment by liyujiang-gzu** [comment]
> OAIDLog.print("Get uuid from preferences: " + uuid); 这边有输出

这个不是oaid，这个是自己生成的uuid（UUID.randomUUID().toString()）
