### ISSUE TITLE
想问下 在权限里面加maxSdkVersion的用意

### ISSUE THREAD

**Issue by kokobebekoko** [gzu-liyujiang/Android_CN_OAID#25]
这完全没办法动态声明权限啊

**Comment by liyujiang-gzu** [comment]
> 这完全没办法动态声明权限啊

maxSdkVersion="29"的意思是在Android 10以上版本不加入这个权限，READ_PHONE_STATE在Android 10以上版本加入了都是没用的，已经不允许获取电话相关硬件信息。

**Comment by liyujiang-gzu** [comment]
> 这完全没办法动态声明权限啊

可以通过下面这个覆盖`Android_CN_OAID`里声明的：
```xml
    <uses-permission
        android:name="android.permission.READ_PHONE_STATE"
        tools:node="replace" />
    <uses-permission
        android:name="android.permission.READ_EXTERNAL_STORAGE"
        tools:node="replace" />
    <uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        tools:node="replace" />
```

**Comment by kokobebekoko** [comment]
> ```
> <uses-permission
>         android:name="android.permission.READ_PHONE_STATE"
>         tools:node="replace" />
>     <uses-permission
>         android:name="android.permission.READ_EXTERNAL_STORAGE"
>         tools:node="replace" />
>     <uses-permission
>         android:name="android.permission.WRITE_EXTERNAL_STORAGE"
>         tools:node="replace" />
> ```

好的谢谢

**Comment by UserName-Haha** [comment]
建议去掉 maxSdkVersion 属性，否则会导致在应用权限列表里都没有此项权限，读写权限都无法请求。出了问题也不好排查，我这上传头像需要读取相册文件，一直提示没权限，我最后实在没办法了反编译看了清单文件才发现问题所在，最后逐个逐个查看三方库清单文件才找到

**Comment by liyujiang-gzu** [comment]
> 建议去掉 maxSdkVersion 属性，否则会导致在应用权限列表里都没有此项权限，读写权限都无法请求。出了问题也不好排查，我这上传头像需要读取相册文件，一直提示没权限，我最后实在没办法了反编译看了清单文件才发现问题所在，最后逐个逐个查看三方库清单文件才找到

的确，maxSdkVersion 属性要慎用

**Comment by liyujiang-gzu** [comment]
> 建议去掉 maxSdkVersion 属性，否则会导致在应用权限列表里都没有此项权限，读写权限都无法请求。出了问题也不好排查，我这上传头像需要读取相册文件，一直提示没权限，我最后实在没办法了反编译看了清单文件才发现问题所在，最后逐个逐个查看三方库清单文件才找到

[最新代码](https://github.com/gzu-liyujiang/Android_CN_OAID/commit/42fe25518615a802b407a0b8e74705920310cb1e)已经去掉了`EXTERNAL_STORAGE` 的 `maxSdkVersion="29"` 限制了的，稍候发布一个`4.1.4`版本

**Comment by liyujiang-gzu** [comment]
> 建议去掉 maxSdkVersion 属性，否则会导致在应用权限列表里都没有此项权限，读写权限都无法请求。出了问题也不好排查，我这上传头像需要读取相册文件，一直提示没权限，我最后实在没办法了反编译看了清单文件才发现问题所在，最后逐个逐个查看三方库清单文件才找到

maxSdkVersion="29" 限制只会导致Android11+没有这个权限，低版本的还是权限的，这个对`READ_PHONE_STATE`及`WRITE_SETTINGS`这种高版本完全禁用调用了的权限很有必要。

**Comment by UserName-Haha** [comment]
> > 建议去掉 maxSdkVersion 属性，否则会导致在应用权限列表里都没有此项权限，读写权限都无法请求。出了问题也不好排查，我这上传头像需要读取相册文件，一直提示没权限，我最后实在没办法了反编译看了清单文件才发现问题所在，最后逐个逐个查看三方库清单文件才找到
> 
> maxSdkVersion="29" 限制只会导致Android11+没有这个权限，低版本的还是权限的，这个对`READ_PHONE_STATE`及`WRITE_SETTINGS`这种高版本完全禁用调用了的权限很有必要。



> > 建议去掉 maxSdkVersion 属性，否则会导致在应用权限列表里都没有此项权限，读写权限都无法请求。出了问题也不好排查，我这上传头像需要读取相册文件，一直提示没权限，我最后实在没办法了反编译看了清单文件才发现问题所在，最后逐个逐个查看三方库清单文件才找到
> 
> maxSdkVersion="29" 限制只会导致Android11+没有这个权限，低版本的还是权限的，这个对`READ_PHONE_STATE`及`WRITE_SETTINGS`这种高版本完全禁用调用了的权限很有必要。

对的，高版本还是有的只是在Android11及以上会存在此问题，感谢修复。

**Comment by liyujiang-gzu** [comment]
@kokobebekoko @UserName-Haha 依赖一下`4.1.4`及其之后的版本就行
