### ISSUE TITLE
4.1.3编译不通过，提示Missing 'package' key attribute on element package

### ISSUE THREAD

**Issue by WangPe1n** [gzu-liyujiang/Android_CN_OAID#26]
Error:
Missing 'package' key attribute on element package at [com.github.gzu-liyujiang:Android_CN_OAID:4.1.3] AndroidManifest.xml

![image](https://user-images.githubusercontent.com/22020970/120624332-2c747b80-c493-11eb-89d2-70a5e688f078.png)

**Comment by liyujiang-gzu** [comment]
> Error:
> Missing 'package' key attribute on element package at [com.github.gzu-liyujiang:Android_CN_OAID:4.1.3] AndroidManifest.xml
> 
> ![image](https://user-images.githubusercontent.com/22020970/120624332-2c747b80-c493-11eb-89d2-70a5e688f078.png)

指向的是清单文件中这两处合并失败，你的Android Studio版本是多少？我这里没问题：
![image](https://user-images.githubusercontent.com/16816717/120758329-47eb8f00-c544-11eb-8cd0-336ce93a48c4.png)

**Comment by liyujiang-gzu** [comment]
那两句是用来兼容Android 11 的谷歌广告ID的，如果您使用的 `Android Gradle 插件版本是 4.1 和以上版本`的话，就可以正常使用新的 元素，因为旧版本的 Gradle 插件并不兼容此元素。

**Comment by liyujiang-gzu** [comment]
不能升级到目前的最新版本`4.2.1`的Android Studio 及 Gradle插件的话，可以把Gradle插件升级到`4.0.1`:
···groovy
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.1'
    }
}
···

![微信截图_20210604150203](https://user-images.githubusercontent.com/16816717/120759719-e2000700-c545-11eb-854b-fb88e8615f8b.png)

**Comment by WangPe1n** [comment]
是的  我把gradle升级到了6.7.1   然后gradle插件升级到了4.2.1  问题解决了

**Comment by liyujiang-gzu** [comment]
实在不能升级Gradle 插件版本的话。可以在你APP的Manifest里加入试试下面这个移除：
```
<queries tools:node="node" />
```

**Comment by WangPe1n** [comment]
> 实在不能升级Gradle 插件版本的话。可以在你APP的Manifest里加入试试下面这个移除：
> 
> ```
> <queries tools:node="remove" />
> ```

好的  谢谢

**Comment by stevenwsg** [comment]
> 实在不能升级Gradle 插件版本的话。可以在你APP的Manifest里加入试试下面这个移除：
> 
> ```
> <queries tools:node="remove" />
> ```

这个具体加在那个位置啊

**Comment by liyujiang-gzu** [comment]
> > 实在不能升级Gradle 插件版本的话。可以在你APP的Manifest里加入试试下面这个移除：
> > ```
> > <queries tools:node="remove" />
> > ```
> 
> 这个具体加在那个位置啊

你自己的APP的`AndroidManiest.xml`的`manifest`节点，如：
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <queries tools:node="remove" />
    
    <application>...</application>
</manifest>
```

**Comment by ka0816** [comment]
<queries tools:node="remove" />
