### ISSUE TITLE
有无考虑使用jni来实现，感觉纯java实现也会出现一些安全性问题

### ISSUE THREAD

**Issue by amlloc** [gzu-liyujiang/Android_CN_OAID#29]

**Comment by liyujiang-gzu** [comment]
安全性问题指的是？

**Comment by amlloc** [comment]
> 安全性问题指的是？

我这边打算把设备唯一性的代码都迁移到c去实现了。多谢开源作为参考~

**Comment by amlloc** [comment]
> 安全性问题指的是？

请教下你是逆向分析拿到的oaid技术方案吗？我看了那个sdk做了加固

**Comment by liyujiang-gzu** [comment]
> > 安全性问题指的是？
> 
> 请教下你是逆向分析拿到的oaid技术方案吗？我看了那个sdk做了加固

我们目前的设备唯一性标识只用来简单的标识客户端唯一性，对安全性要求不高，没用到一个设备只允许一定次数的抢红包、领福利之类的场景，所以不需要要对设备标识的生成算法做加密。**对于需要保密设备唯一标识生成算法的，放在jni去实现并不可考，强烈建议放在服务端进行实现，客服端只负责采集原始的IMEI、OAID之类的标识**。

本项目的 OAID 获取接口主要参考**北京数字联盟公开的代码**以及逆向分析参考**移动安全联盟的 SDK**、**HUAWEI Ads SDK**、**小米 DeviceId.jar**、**Google Play Services SDK **等。

**Comment by amlloc** [comment]
> > > 安全性问题指的是？
> > 
> > 
> > 请教下你是逆向分析拿到的oaid技术方案吗？我看了那个sdk做了加固
> 
> 我们目前的设备唯一性标识只用来简单的标识客户端唯一性，对安全性要求不高，没用到一个设备只允许一定次数的抢红包、领福利之类的场景，所以不需要要对设备标识的生成算法做加密。 **对于需要保密设备唯一标识生成算法的，放在jni去实现并不可考，强烈建议放在服务端进行实现，客服端只负责采集原始的IMEI、OAID之类的标识** 。
> 
> 本项目的 OAID 技术方案主要参考 **北京数字联盟公开的代码** 以及逆向分析参考 **移动安全联盟的 SDK** 、 **HUAWEI Ads SDK** 、 **小米 DeviceId.jar** 、 **Google Play Services SDK** 。

好的，谢谢~
