### ISSUE TITLE
小米MIX

### ISSUE THREAD

**Issue by echo6106** [gzu-liyujiang/Android_CN_OAID#3]
java.lang.NoSuchMethodException: getDefaultUDID [class android.content.Context]

**Comment by echo6106** [comment]
: java.lang.NoSuchMethodException: getDefaultUDID [class android.content.Context]
08-18 20:26:04.483 W/System.err(23013): 	at java.lang.Class.getMethod(Class.java:2068)
08-18 20:26:04.483 W/System.err(23013): 	at java.lang.Class.getMethod(Class.java:1690)
08-18 20:26:04.483 W/System.err(23013): 	at com.github.gzuliyujiang.oaid.impl.XiaomiDeviceIdImpl.doGet(XiaomiDeviceIdImpl.java:67)

**Comment by echo6106** [comment]
Android8.0.0

**Comment by liyujiang-gzu** [comment]
> Android8.0.0

小米8.0.0应该是不支持获取OAID

**Comment by echo6106** [comment]
小米MIX 一代不支持
