### ISSUE TITLE
OAID存储

### ISSUE THREAD

**Issue by stevenwsg** [gzu-liyujiang/Android_CN_OAID#33]
OAID能否用Sp进行存储，这样的话每次APP启动的时候，从sp拿到的oaid并不为空。 拿到OAID的时候刷新sp。

每次初始化去拿的话会有一个问题， 就是打点时机比较早的话，可能还没有拿到oaid，导致上报为空。后续上报不为空。

或者在向外暴露一个获取oaid成功的接口，由开发者自己处理oaid的存储和一些其他操作。自由度也会比较高一些

**Comment by liyujiang-gzu** [comment]
> OAID能否用Sp进行存储，这样的话每次APP启动的时候，从sp拿到的oaid并不为空。 拿到OAID的时候刷新sp。
> 
> 每次初始化去拿的话会有一个问题， 就是打点时机比较早的话，可能还没有拿到oaid，导致上报为空。后续上报不为空。
> 
> 或者在向外暴露一个获取oaid成功的接口，由开发者自己处理oaid的存储和一些其他操作。自由度也会比较高一些

OAID可以用Sp进行存储的。适时获取oaid成功的接口也是有的`DeviceID.getOAID(new IGetter(){...})`。

**Comment by stevenwsg** [comment]
> > OAID能否用Sp进行存储，这样的话每次APP启动的时候，从sp拿到的oaid并不为空。 拿到OAID的时候刷新sp。
> > 每次初始化去拿的话会有一个问题， 就是打点时机比较早的话，可能还没有拿到oaid，导致上报为空。后续上报不为空。
> > 或者在向外暴露一个获取oaid成功的接口，由开发者自己处理oaid的存储和一些其他操作。自由度也会比较高一些
> 
> OAID可以用Sp进行存储的。适时获取oaid成功的接口也是有的`DeviceID.getOAID(new IGetter(){...})`。

嗯嗯 ，就是把 DeviceID.register方法移到Application里面是吧

**Comment by liyujiang-gzu** [comment]
> > > OAID能否用Sp进行存储，这样的话每次APP启动的时候，从sp拿到的oaid并不为空。 拿到OAID的时候刷新sp。
> > > 每次初始化去拿的话会有一个问题， 就是打点时机比较早的话，可能还没有拿到oaid，导致上报为空。后续上报不为空。
> > > 或者在向外暴露一个获取oaid成功的接口，由开发者自己处理oaid的存储和一些其他操作。自由度也会比较高一些
> > 
> > 
> > OAID可以用Sp进行存储的。适时获取oaid成功的接口也是有的`DeviceID.getOAID(new IGetter(){...})`。
> 
> 嗯嗯 ，就是把 DeviceID.register方法移到Application里面是吧

> OAID能否用Sp进行存储，这样的话每次APP启动的时候，从sp拿到的oaid并不为空。 拿到OAID的时候刷新sp。
> 
> 每次初始化去拿的话会有一个问题， 就是打点时机比较早的话，可能还没有拿到oaid，导致上报为空。后续上报不为空。
> 
> 或者在向外暴露一个获取oaid成功的接口，由开发者自己处理oaid的存储和一些其他操作。自由度也会比较高一些

你的这种需求，不用`DeviceID.register(Application)`的方式预先获取客户端标识，可以自己调用自由度更高的那几个方法（getUniqueID、getOAID、getAndroidID、getUUID）自行得到客户端唯一标识。

**Comment by liyujiang-gzu** [comment]
> OAID能否用Sp进行存储，这样的话每次APP启动的时候，从sp拿到的oaid并不为空。 拿到OAID的时候刷新sp。
> 
> 每次初始化去拿的话会有一个问题， 就是打点时机比较早的话，可能还没有拿到oaid，导致上报为空。后续上报不为空。
> 
> 或者在向外暴露一个获取oaid成功的接口，由开发者自己处理oaid的存储和一些其他操作。自由度也会比较高一些

自4.2.6版本开始已提供回调接口
