### ISSUE TITLE
荣耀手机获取失败，是不支持吗，官网V1.0.26好像可以支持

### ISSUE THREAD

**Issue by hanxuefengshuang** [gzu-liyujiang/Android_CN_OAID#36]
接的一些第三方sdk需要传oaid，测试荣耀手机获取不到

**Comment by liyujiang-gzu** [comment]
> 接的一些第三方sdk需要传oaid，测试荣耀手机获取不到

官网V1.0.26的包能发一个来嘛，我没有企业信息注册账号他不让我下载。看官方的日志，V1.0.26加了一些支持：
```text
2021年7月2日 version 1.0.26
      1.增加支持荣耀、realme、酷赛、Cool OS；
      2.增加包名校验机制；
      3.更新加固方案；
      4.增加补充设备标识符开关接口。
```

**Comment by hanxuefengshuang** [comment]
测试已经可以获取了，太棒了

**Comment by liyujiang-gzu** [comment]
> 测试已经可以获取了，太棒了

之前不是说获取失败吗

**Comment by hanxuefengshuang** [comment]
> > 测试已经可以获取了，太棒了
> 
> 以前不是说获取失败吗


> > 测试已经可以获取了，太棒了
> 
> 以前不是说获取失败吗

之前那个是第三方arr包内它自己获取的，它没用我传过去的值，我以为没获取到 传了个空值过去，它包内是没有获取到的，但是我用这个包调试发现已经是有值的

**Comment by liyujiang-gzu** [comment]
> > > 测试已经可以获取了，太棒了
> > 
> > 
> > 以前不是说获取失败吗
> 
> > > 测试已经可以获取了，太棒了
> > 
> > 
> > 以前不是说获取失败吗
> 
> 之前那个是第三方arr包内它自己获取的，它没用我传过去的值，我以为没获取到 传了个空值过去，它包内是没有获取到的，但是我用这个包调试发现已经是有值的

我用云真机测试了很多个，国内主流手机厂商基本上都是支持了的
