### ISSUE TITLE
小米云测平台 红米 K20 兼容性测试崩溃

### ISSUE THREAD

**Issue by tudoutiao** [gzu-liyujiang/Android_CN_OAID#39]
打包提交小米平台提示兼容性不通过，在云测平台测试  红米K20 报错 。
小米云测地址
https://testit.miui.com/task/create/compatibility
![image](https://user-images.githubusercontent.com/10770339/133883834-eb5e38a9-1ab4-4076-a308-43b675550a64.png)

**Comment by liyujiang-gzu** [comment]
我试了没奔溃，真机试了是ANR
![image](https://user-images.githubusercontent.com/16816717/133932886-837f43cf-e95e-4884-aeee-39de44ff1ab7.png)
