### ISSUE TITLE
那问下作者，这个Android_CN_OAID和移动安全联盟的miit_mdid_1.0.10有什么不同呢？

### ISSUE THREAD

**Issue by oldsboy** [gzu-liyujiang/Android_CN_OAID#4]
![image](https://user-images.githubusercontent.com/33484768/91290261-fc8e9e00-e7c5-11ea-8c25-28ba1da654f4.png)
rt

**Comment by liyujiang-gzu** [comment]
一样的功能。只是移动安全联盟的是官方权威，他们直接和各大厂商合作，但是他们的SDK过度的通过C/C++层加固封闭，出了问题不好定位分析。
