### ISSUE TITLE
不同手机具有相同的clientIdMd5

### ISSUE THREAD

**Issue by JadePeakPoet** [gzu-liyujiang/Android_CN_OAID#43]
目前统计重复的有两个(线上实际用户统计)

相关文章(文章中包含了我所碰到的两种类型错误，除此之外还有空值，null的情形，"null"字符串)
设备ID又一坑【抛砖引玉】
https://zhuanlan.zhihu.com/p/63708748

IMEI变成0了 
http://www.oneplusbbs.com/thread-4331675-1.html

1
9f89c84a559f573636a47ff8daed0d33
md5前的源数据为00000000-0000-0000-0000-000000000000
大量存在于华为/荣耀手机中，应该是华为手机的广告标识符(idfa)，占比极高，大概能占据华为手机用户的1/5

2
cd9e459ea708a948d5c2f5a6ca8838cf
md5前的源数据为0，推测位imei

占比较少，存在于少量魅族和个别华为手机中，网络上有一加手机，小米手机案例，根据网络信息推测大概率为用户刷机所致

这部分特殊数据可能需要做下过滤

**Comment by JadePeakPoet** [comment]
看到之前其他类似讨论的帖子了，决定暂时用之前存储的其他字段去做进一步分析，也可能自己在Android项目里做下兼容过滤

**Comment by liyujiang-gzu** [comment]
> 看到之前其他类似讨论的帖子了，决定暂时用之前存储的其他字段去做进一步分析，也可能自己在Android项目里做下兼容过滤

OAID为`00000000-0000-0000-0000-000000000000`是用户关闭了广告标识符；IMEI为0也许是用户拒绝了相关权限。本库之前没考虑到这两种情况，可以自己在Android项目里做下兼容过滤。
