### ISSUE TITLE
关于 queries 配置的问题

### ISSUE THREAD

**Issue by YueJZSensorsData** [gzu-liyujiang/Android_CN_OAID#44]
我测试模拟器、华为、oppo 机型，在 Android 11 以上的机器测试，不配置 queries 也可以获取 OAID，请问大佬为什么还需要配置？

![image](https://user-images.githubusercontent.com/36151500/156119136-a195aabd-2048-4be4-9f0f-ac5e32f88d40.png)

**Comment by liyujiang-gzu** [comment]
会不会是你加入了“android.permission.QUERY_ALL_PACKAGES”权限了？或者是将应用的 targetSdkVersion 设为 30 以下了？

**Comment by YueJZSensorsData** [comment]
并没有，我是直接利用你的 demo 测试的，只是把 queries 注销了，我反编译看，权限和 targetSdkVersion 都没有问题呀

![image](https://user-images.githubusercontent.com/36151500/156126085-cabfdab6-edaf-4bee-94ff-8824f28718d7.png)

![image](https://user-images.githubusercontent.com/36151500/156126168-e2de3511-3326-4ae5-85b7-8801c6c92f9b.png)

[app-dev-arm64-v8a-debug.apk.zip](https://github.com/gzu-liyujiang/Android_CN_OAID/files/8159670/app-dev-arm64-v8a-debug.apk.zip)

**Comment by liyujiang-gzu** [comment]
> 并没有，我是直接利用你的 demo 测试的，只是把 queries 注销了，我反编译看，权限和 targetSdkVersion 都没有问题呀
> 

那就不清楚了，安卓开发文档说的目标Android 11+不加queries将无法调用相关的包，也说了部分包可能自动可见：https://developer.android.google.cn/about/versions/11/privacy/package-visibility?hl=zh-cn
![image](https://user-images.githubusercontent.com/16816717/156139136-e28e8103-dc64-4f78-85ac-eece7457cf26.png)
