### ISSUE TITLE
这个混淆规则好像有问题，Google服务手机上获取OAID崩溃了

### ISSUE THREAD

**Issue by mrduank** [gzu-liyujiang/Android_CN_OAID#49]
这边发现混淆规则里面少了对Google的混淆，麻烦看一下，我这边手动新增了两个混淆：
-keep class repeackage.com.google.android.gms.ads.identifier.internal.** { *; }
-keep interface repeackage.com.google.android.gms.ads.identifier.internal.** { *; }

**Comment by liyujiang-gzu** [comment]
嗯，是要加上这个
