### ISSUE TITLE
获取oiad错误

### ISSUE THREAD

**Issue by cui19951005** [gzu-liyujiang/Android_CN_OAID#5]
提示com.github.gzuliyujiang.oiad.impl.XiaomiDeviceIdImple@1e6ad75

**Comment by liyujiang-gzu** [comment]
是Android 10么，小米的要MIUI10.2 及以上才支持获取OAID

**Comment by godvmxi** [comment]
。。。发布成jar吧。。。我试着做成aar给unity用。

**Comment by liyujiang-gzu** [comment]
#6 应该是将deviceId重命名为oaid的时候出的问题
