### ISSUE TITLE
请问该库商用有法律风险吗？

### ISSUE THREAD

**Issue by pantaopt** [gzu-liyujiang/Android_CN_OAID#50]
鉴于安全联盟下载SDK需要被审核，审核内容包括企业资质。顾提出这个问题，想确认一遍。感谢！

**Comment by pantaopt** [comment]
https://github.com/gzu-liyujiang/Android_CN_OAID/issues/41
这个issue有朋友提出了该开源项目可否商用？已关注到。
本人想提出的是关于内置获取各大厂商OAID方法，是否影响到安全联盟，从而被影响商用。

**Comment by liyujiang-gzu** [comment]
> #41 这个issue有朋友提出了该开源项目可否商用？已关注到。 本人想提出的是关于内置获取各大厂商OAID方法，是否影响到安全联盟，从而被影响商用。

内置获取各大厂商OAID方法和安全联盟没直接关系，OAID作为行业标准，理论上应该没有商用风险，但不排除有被找麻烦的风险，不过至少有北京数盟这种公司顶着，下面是数盟的声明参考。
![image](https://user-images.githubusercontent.com/16816717/168807324-589e471c-02d0-4b1e-b5cf-a2c3164406bc.png)

**Comment by liyujiang-gzu** [comment]
> 鉴于安全联盟下载SDK需要被审核，审核内容包括企业资质。顾提出这个问题，想确认一遍。感谢！

依据《中华人民共和国标准化法》，OAID行业标准是公开的，这个项目的开源方案和移动安全联盟的SDK应该是属于市场竞争行为，不得被标准限制，搞垄断。

**Comment by liyujiang-gzu** [comment]
@pantaopt 可能存在的麻烦风险在于其中的`MsaIdInterface.aidl`，这个是移动安全联盟定义的开放匿名设备标识符接口，逆向得来的

**Comment by liyujiang-gzu** [comment]
当初我创建这个项目的初衷，主要也是因为移动安全联盟的SDK需要企业资质，对个人开发者不友好，不利于OAID标准的普及。作为个人开发者的话，移动安全联盟才没那种闲情来找麻烦。企业用户的话，能用移动安全联盟的SDK的话尽量用移动安全联盟的SDK。

**Comment by pantaopt** [comment]
我可能是意念回复了。。。

**Comment by pantaopt** [comment]
感谢解答，解答的很细致。
我这边关掉这个issue吧。
感谢巨佬为我们伸手党谋福祉。👍🏻👍🏻

**Comment by liyujiang-gzu** [comment]
之前的参考资料之一  https://github.com/2tu/msa 居然被 MSA 举报，作为行业技术标准还兴搞技术垄断，要使用 MSA 的 SDK 真实一言难尽啊，参见： https://github.com/github/dmca/blob/master/2023/09/2023-09-21-msa.md

**Comment by liyujiang-gzu** [comment]
> 之前的参考资料之一 https://github.com/2tu/msa 居然被 MSA 举报，作为行业技术标准还兴搞技术垄断，要使用 MSA 的 SDK 真实一言难尽啊，参见： https://github.com/github/dmca/blob/master/2023/09/2023-09-21-msa.md

对于个人开发者没有资质使用 MSA 的 SDK 这件事，而且他们联盟的单位并不完全公开OAID的调用方式，我感觉有理由认为他们的行为违反了《中华人民共和国标准法》。
