### ISSUE TITLE
按照文档接入，无法依赖这个库。

### ISSUE THREAD

**Issue by chenjiaming2qiqi** [gzu-liyujiang/Android_CN_OAID#52]
Failed to resolve: com.github.gzu-liyujiang:Android_CN_OAID:4.2.4

**Comment by chenjiaming2qiqi** [comment]
gradle版本是7.1

**Comment by chenjiaming2qiqi** [comment]
implementation 'com.github.gzu-liyujiang:Android_CN_OAID:4.2.4'

**Comment by liyujiang-gzu** [comment]
参阅 https://jitpack.io/#gzu-liyujiang/Android_CN_OAID

**Comment by GuLiPing-Hz** [comment]
新项目无法依赖

**Comment by GuLiPing-Hz** [comment]
Could not resolve com.github.gzu-liyujiang:Android_CN_OAID:4.2.4

**Comment by liyujiang-gzu** [comment]
> Could not resolve com.github.gzu-liyujiang:Android_CN_OAID:4.2.4
> 
> 复现方法很简单，把android studio关掉。到【C:\Users\Administrator.gradle】这个目录改名成 .gradle1,重启android studio。刷新就复现了。建议出个aar版本。目前我试了好几次都下不下来！！！

最新aar已经上传：https://github.com/gzu-liyujiang/Android_CN_OAID/releases/download/4.2.4/library-4.2.4-6-g22e095d.aar

**Comment by liyujiang-gzu** [comment]
每次发布新版本，都会上传aar文件的，参见 https://github.com/gzu-liyujiang/Android_CN_OAID/releases

**Comment by liyujiang-gzu** [comment]
> gradle版本是7.1

gradle 7.x 版本需要在setting.gradle里添加 jitpack 的仓库地址。
