### ISSUE TITLE
安裝Demo.apk後，啟動遇到Google Play提示不明來源

### ISSUE THREAD

**Issue by dokinkon** [gzu-liyujiang/Android_CN_OAID#53]
請參考截圖

[https://imgur.com/8K6txOv](url)

請問原因以及是否有可能解法？

**Comment by liyujiang-gzu** [comment]
> 請參考截圖
> 
> [https://imgur.com/8K6txOv](url)
> 
> 請問原因以及是否有可能解法？

你这个报毒的详情能展开看看是啥吗？我这里没报毒。
![Screenshot_2022-06-01-21-58-09-587_com miui home](https://user-images.githubusercontent.com/16816717/171422395-e0054b3b-9730-48ef-99ff-09256af3f41a.jpg)

**Comment by dokinkon** [comment]
大佬再問一個問題，本來我們家的apk沒有上架Google Play，但是安裝時Google Play也不會跳出任何訊息，但是接入OAID之後就跳了，我直接打包Demo.apk也是相同的情況，請問可能的原因是哪一段造成的呢？
先謝謝大佬了～

**Comment by liyujiang-gzu** [comment]
> 大佬再問一個問題，本來我們家的apk沒有上架Google Play，但是安裝時Google Play也不會跳出任何訊息，但是接入OAID之後就跳了，我直接打包Demo.apk也是相同的情況，請問可能的原因是哪一段造成的呢？ 先謝謝大佬了～

估计是获取了安卓广告标识符（AAID）、IMEI等相关隐私标识。

**Comment by liyujiang-gzu** [comment]
> 大佬再問一個問題，本來我們家的apk沒有上架Google Play，但是安裝時Google Play也不會跳出任何訊息，但是接入OAID之後就跳了，我直接打包Demo.apk也是相同的情況，請問可能的原因是哪一段造成的呢？ 先謝謝大佬了～

`GmsImpl.java`的以下代码使用了Google Play服务，因此未上架应用商店Google Play才提示吧：
```java
    Intent intent = new Intent("com.google.android.gms.ads.identifier.service.START");
    intent.setPackage("com.google.android.gms");
```

**Comment by dokinkon** [comment]
明白謝謝大佬
