### ISSUE TITLE
getWidevineID 使用MediaDrm 部分手机异常

### ISSUE THREAD

**Issue by w296365959** [gzu-liyujiang/Android_CN_OAID#55]
OPPO R11 Android 7.1.1 API25
错误信息
  at android.media.MediaDrm.native_setup(Native method)
  at android.media.MediaDrm.<init>(MediaDrm.java:282)

**Comment by pwj1568** [comment]
我也遇到了，在大疆的带屏遥控器 DJI RC Pro（RM510）上也是这里报错。

**Comment by liyujiang-gzu** [comment]
drm的id很鸡肋，部分手机会卡死或闪退，自4.2.7版本后已标记废弃，默认不再尝试获取该ID。
