### ISSUE TITLE
WidevineID唯一性

### ISSUE THREAD

**Issue by fioogle** [gzu-liyujiang/Android_CN_OAID#61]
> ```
>     官方建议是WidevineID
>    https://developer.android.com/training/articles/user-data-ids
>    
>    https://stackoverflow.com/questions/67396257
>    从这个提问来看，唯一性可能有点问题
> ```
- IMEI：Android 10+ 获取不到了；
- AAID：系统需自带 Google Play Services 才支持，且用户可以在系统设置中重置；
- OAID：基本上是国内知名厂商 Android 10+ 才支持，且用户可以在系统设置中重置；
- AndroidID：可能为空；
- PseudoID：可能重复；
- GUID：Android 10+ 卸载APP后会丢失；
- WidevineID：未经过验证，不知道可靠性如何；

最好是**通过服务端从以上标识中通过拜占庭容错方案得到可靠的设备唯一标识**。不能使用服务端的话，综合来看 AndroidID 和 OAID 相对可靠一些吧，项目中我**已经提供了一个`getClientId`/`getClientIdMd5`/`getClientIdSha1`获取客户端唯一标识**，依次获取IMEI、AndroidID、OAID、WidevineID、GUID……

_Originally posted by @liyujiang-gzu in https://github.com/gzu-liyujiang/Android_CN_OAID/issues/28#issuecomment-858218231_

**Comment by liyujiang-gzu** [comment]
这个地址不用翻墙访问：https://developer.android.google.cn/training/articles/user-data-ids

**Comment by liyujiang-gzu** [comment]
WidevineID很鸡肋，食之无味，弃之可惜，在一些国产手机上会造成闪退或卡死，自4.2.7版本已标记废弃。
