### ISSUE TITLE
请教大佬后端唯一标识真假判断问题。

### ISSUE THREAD

**Issue by cjlovefree** [gzu-liyujiang/Android_CN_OAID#62]
请问大佬，取出这个唯一标识后，后端怎么验证这个唯一标识是正确的而不是伪造的？

**Comment by tanranran** [comment]
除非能拿到厂商生成OAID的算法，否则没法判断

**Comment by sisuad** [comment]
通过官方的sdk再拿一次，每次对比，监听双方不一致情况，放到线上跑一段时间就知道了
