### ISSUE TITLE
大佬 华为需要适配了 

### ISSUE THREAD

**Issue by limoxiao** [gzu-liyujiang/Android_CN_OAID#66]
华为最新鸿蒙系统 咱们这个库已经无法兼容了（ 华为HMS Core 6.10.4.302版本以上获取不到OAID）  华为最新oaid获取文档  https://developer.huawei.com/consumer/cn/doc/development/HMSCore-Guides/identifier-service-integrating-sdk-0000001056460552
大佬有时间辛苦兼容下

**Comment by dreamofwarmcolor** [comment]
坐等大佬的解决方案~

**Comment by liyujiang-gzu** [comment]
@limoxiao @dreamofwarmcolor 已适配

**Comment by fza3230200** [comment]
> @limoxiao @dreamofwarmcolor 已适配，版本号 [4.2.5.1](https://github.com/gzu-liyujiang/Android_CN_OAID/releases/tag/4.2.5.1)
咱们是否有办法不用华为的sdk呢？

**Comment by liyujiang-gzu** [comment]
> > @limoxiao @dreamofwarmcolor 已适配，版本号 [4.2.5.1](https://github.com/gzu-liyujiang/Android_CN_OAID/releases/tag/4.2.5.1)
> > 咱们是否有办法不用华为的sdk呢可以反编译

> > @limoxiao @dreamofwarmcolor 已适配，版本号 [4.2.5.1](https://github.com/gzu-liyujiang/Android_CN_OAID/releases/tag/4.2.5.1)
> > 咱们是否有办法不用华为的sdk呢？

可以反编译他SDK，参考里面的核心逻辑重写

**Comment by sunshuai212** [comment]
依赖华为的sdk和安全联盟官方的sdk就会有冲突了

**Comment by liyujiang-gzu** [comment]
> 依赖华为的sdk和安全联盟官方的sdk就会有冲突了

的确是，我倒忽略了这个和安全联盟官方的sdk共存的问题

**Comment by liyujiang-gzu** [comment]
> 依赖华为的sdk和安全联盟官方的sdk就会有冲突了

**4.2.5.1 版本以后直接使用了华为官方广告标识服务SDK，与移动安全联盟 SDK 共存** 的话可参考如下配置：
```groovy
dependencies {
    implementation('com.github.gzu-liyujiang:Android_CN_OAID:<version>') {
        // 排除掉本项目依赖的华为官方广告标识服务SDK，也即是使用移动安全联盟SDK依赖的华为官方广告标识服务SDK
        exclude group: 'com.huawei.hms', module: 'ads-identifier' 
    }
}
```

**Comment by liupe** [comment]
> > 依赖华为的sdk和安全联盟官方的sdk就会有冲突了
> 
> **4.2.5.1 版本以后直接使用了华为官方广告标识服务SDK，与移动安全联盟 SDK 共存** 的话可参考如下配置：
> 
> ```groovy
> dependencies {
>     implementation('com.github.gzu-liyujiang:Android_CN_OAID:<version>') {
>         // 排除掉本项目依赖的华为官方广告标识服务SDK，也即是使用移动安全联盟SDK依赖的华为官方广告标识服务SDK
>         exclude group: 'com.huawei.hms', module: 'ads-identifier' 
>     }
> }
> ```

大佬，现在移动安全联盟的sdk也获取办不到华为手机的OAID吧，他们好像没更新最新的华为官方标识服务SDK。

**Comment by csh159** [comment]
鸿蒙系统  4.2.5.1闪退

**Comment by shaunheilee** [comment]
> 鸿蒙系统 4.2.5.1闪退
dependency 里边添加 ads-identifier 的依赖即可
implementation 'com.huawei.hms:ads-identifier:3.4.62.300'

**Comment by csh159** [comment]
> > 鸿蒙系统 4.2.5.1闪退
> 
> dependency 里边添加 ads-identifier 的依赖即可 `implementation 'com.huawei.hms:ads-identifier:3.4.62.300'`

加了上面的不闪退了，但是获取oaid为空

**Comment by tegabom** [comment]
You can contact me for full working version of O11 OTT Streamer V2!!! Latest Build!!!

https://t.me/zaddyst

- License Offline and install Unlimited servers
- Script Autoinstall and Autorestart
O11 v2 supports 5 running modes
- Internal remuxer
- FFmpeg resident
- FFmpeg TS HLS/Direct
- FFmpeg MultiTS HLS
- FMP4 HL
O11 v2 supports 5 output modes
- HLS/Direct
- SRT Server
- Custom Pipe
- UDP/SRT Push
- MPEGTS
Ondemand function
- Network Params
- HTTP/SOCKS5 Proxy
- Bind
- DNS over HTTPS
- Script,Manifest,Media files
Scripts
action=manifest - Manifest script
action=cdm drm=[widevine or playready] cdm=[internal or external] challenge=[drm challenger] pssh=[pssh used to extract needed keys] - Cdm script
action=events - Events
action=channels - Channels
action - Heartbeat
