### ISSUE TITLE
华为设备崩溃

### ISSUE THREAD

**Issue by Ylarod** [gzu-liyujiang/Android_CN_OAID#69]
```
java.lang.NoClassDefFoundError:Failed resolution of: Lcom/huawei/hms/ads/identifier/AdvertisingIdClient;
com.github.gzuliyujiang.oaid.impl.HuaweiImpl.doGet(HuaweiImpl.java:66)
Caused by:
java.lang.ClassNotFoundException:com.huawei.hms.ads.identifier.AdvertisingIdClient
com.github.gzuliyujiang.oaid.impl.HuaweiImpl.doGet(HuaweiImpl.java:66)
com.github.gzuliyujiang.oaid.DeviceID.getOAID(DeviceID.java:127)
com.github.gzuliyujiang.oaid.DeviceIdentifier.getOAID(DeviceIdentifier.java:88)
```

![image](https://github.com/gzu-liyujiang/Android_CN_OAID/assets/30978685/e423a4a4-0fc0-4ab6-a03c-ec081609d191)

**Comment by liyujiang-gzu** [comment]
> ```
> java.lang.NoClassDefFoundError:Failed resolution of: Lcom/huawei/hms/ads/identifier/AdvertisingIdClient;
> com.github.gzuliyujiang.oaid.impl.HuaweiImpl.doGet(HuaweiImpl.java:66)
> Caused by:
> java.lang.ClassNotFoundException:com.huawei.hms.ads.identifier.AdvertisingIdClient
> com.github.gzuliyujiang.oaid.impl.HuaweiImpl.doGet(HuaweiImpl.java:66)
> com.github.gzuliyujiang.oaid.DeviceID.getOAID(DeviceID.java:127)
> com.github.gzuliyujiang.oaid.DeviceIdentifier.getOAID(DeviceIdentifier.java:88)
> ```
> 
> ![image](https://user-images.githubusercontent.com/30978685/277894732-e423a4a4-0fc0-4ab6-a03c-ec081609d191.png)

缺少华为广告标识符的包，可添加依赖：
```groovy
runtimeOnly 'com.huawei.hms:ads-identifier:3.4.62.300'
```

**Comment by Ylarod** [comment]
Thanks
