### ISSUE TITLE
引入报错和最新版本问题

### ISSUE THREAD

**Issue by ender115** [gzu-liyujiang/Android_CN_OAID#7]
implementation 'com.github.gzu-liyujiang:Android_CN_OAID:${latest.version}'
您好，我直接这样引入报错，最新版本是1.0.2么

**Comment by ender115** [comment]
IDeviceId deviceId = DeviceID.with(this);
            if (!deviceId.supportOAID()) {
                // 不支持OAID，须自行生成全局唯一标识（GUID）。
                // 本库不提供GUID的生成方式，可以使用`UUID.randomUUID().toString()`生成，
                // 然后存到`SharedPreferences`及`ExternalStorage`甚至`CloudStorage`。
                LogUtils.e("不支持获取oaid");
                FLog.d("IDeviceId  " + "不支持获取oaid");
                return;
            }
            deviceId.doGet(new IOAIDGetter() {
                @Override
                public void onOAIDGetComplete(@NonNull String oaid) {
                    mIMEIId = oaid;
                    LogUtils.e(oaid);
                    FLog.d("onOAIDGetComplete  " + oaid);
                }

                @Override
                public void onOAIDGetError(@NonNull Exception exception) {
                    LogUtils.e(exception.toString());
                    FLog.d("onOAIDGetError  " + exception.toString());
                }
            });
另外这段代码有可能造成应用崩溃么？我再try catch一下应该没什么影响吧

**Comment by liyujiang-gzu** [comment]
最新版本是
[![jitpack](https://jitpack.io/v/gzu-liyujiang/Android_CN_OAID.svg)](https://jitpack.io/#gzu-liyujiang/Android_CN_OAID)

本库已对可能的异常进行捕获处理，发生异常会回调`onOAIDGetError(@NonNull Exception exception)`，再try catch一下是没有影响的。
