### ISSUE TITLE
4.2.8版本远程依赖不了

### ISSUE THREAD

**Issue by liuyaxi** [gzu-liyujiang/Android_CN_OAID#78]
咋回事

**Comment by jiqianwen** [comment]
![QQ截图20231213102210](https://github.com/gzu-liyujiang/Android_CN_OAID/assets/26268908/199f5fc2-9a1b-4178-b2c8-6ddccbf92bec)
荣耀的这个一直依赖不了

**Comment by liuyaxi** [comment]
> ![QQ截图20231213102210](https://private-user-images.githubusercontent.com/26268908/290055298-199f5fc2-9a1b-4178-b2c8-6ddccbf92bec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzQ1MTcsIm5iZiI6MTcwMjQzNDIxNywicGF0aCI6Ii8yNjI2ODkwOC8yOTAwNTUyOTgtMTk5ZjVmYzItOWExYi00MTc4LWIyYzgtNmRkY2NiZjkyYmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDAyMjMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MGE2YjNmZmMxM2Q4ZDA1NGU0Yjc3MjBmYjgyMmM2YjEyZmQyZTQzMzAzODZmOTQ4MzM4ZTlhNDJkNzhhZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9YUcgVaGWB7MAU6HnLaDrHjU1vyF6Oo-5Wv1XgCVRhA) 荣耀的这个一直依赖不了

是下载不了  不知道咋回事

**Comment by jiqianwen** [comment]
buildscript {
    repositories {
        maven { url 'https://developer.hihonor.com/repo' }
    }
}

allprojects {
    repositories {
        maven { url 'https://developer.hihonor.com/repo' }
    }
}

翻了了文档，自己手动加荣耀的maven库地址就好了

**Comment by liuyaxi** [comment]
> maven { url 'https://developer.hihonor.com/repo' }
可以了非常感谢
