### ISSUE TITLE
这个只能在原生安卓使用是吧，unaipp能用吗

### ISSUE THREAD

**Issue by faith1605** [gzu-liyujiang/Android_CN_OAID#79]

**Comment by MaYiFei1995** [comment]
uni支持oaid插件的配置，但版本只是1.0.13[enableOAID](https://uniapp.dcloud.net.cn/collocation/manifest-app.html#enableoaid)
用这个的话，只能是自己封装一个原生插件了

**Comment by faith1605** [comment]
好的谢谢~

**Comment by MaYiFei1995** [comment]
> 好的谢谢~

摸了一个原生插件，可以试一下看 
[Android_CN_OAID_UNI](https://github.com/MaYiFei1995/Android_CN_OAID_UNI)
