### ISSUE TITLE
有没有和移动联盟共存的方案

### ISSUE THREAD

**Issue by Davywsz** [gzu-liyujiang/Android_CN_OAID#8]
我这边的需求是想它和移动联盟共存。但是现在发现aidl的接口是冲突的

**Comment by liyujiang-gzu** [comment]
共存的意义不大吧？都是获取oaid

**Comment by liyujiang-gzu** [comment]
aidl冲突，你可以尝试直接clone源代码，删掉这个库的所以aidl文件试试

**Comment by liyujiang-gzu** [comment]
> 我这边的需求是想它和移动联盟共存。但是现在发现aidl的接口是冲突的

最近我用到了一个广告SDK，该广告SDK自带了移动安全联盟的aar，的确是aidl冲突了，我重新分包，将aidl分离出来可选依赖。
```
    //implementation 'com.github.gzu-liyujiang.Android_CN_OAID:OAID_AIDL:2.0.0'
    implementation 'com.github.gzu-liyujiang.Android_CN_OAID:OAID_IMPL:2.0.0'
```

**Comment by liyujiang-gzu** [comment]
**[4.0.0版本](https://github.com/gzu-liyujiang/Android_CN_OAID/releases/tag/4.0.0)以后重新调整了与移动安全联盟 SDK 共存的方案**，直接使用如下依赖即可：

```groovy
dependencies {
    implementation 'com.github.gzu-liyujiang:Android_CN_OAID:4.0.0'
}
```
