### ISSUE TITLE
OPPO隐私合规问题

### ISSUE THREAD

**Issue by Born-alone** [gzu-liyujiang/Android_CN_OAID#93]
![image](https://github.com/user-attachments/assets/7a9ca35a-2391-47e8-ab66-9264537ea175)
在欢迎页启动前就调用了获取方法  在Application初始话的时候同意了隐私协议才会调用库中相关方法 
目前用的版本是4.2.5.1 这个该如何解决
![image](https://github.com/user-attachments/assets/9caa6198-42c1-4170-953c-3aaa1b8ee384)
![image](https://github.com/user-attachments/assets/81719b7b-cd7d-456e-9af5-0b3bd7485a08)
这边代码只会获取一次 且保证是在用户同意隐私协议后 调用DeviceID.getOAID方法获取后 均会保存至本地 
OPPO那边反馈说多次调用获取OAID 请问咱库这边会有静默获取吗

**Comment by liuxuesong001** [comment]
同问？请问解决了么？

**Comment by Born-alone** [comment]
> 同问？请问解决了么？
更换了MSA 移动安全联盟的第三库 算是解决了吧

**Comment by sophuron** [comment]
我认为是没将本库写到隐私条款中，但通过本库调用了系统oaid的获取方法，所以被oppo定义为静默了。

**Comment by daquanzheng** [comment]
我们的产品现在也遇到了这个问题 OPPO和荣耀都上不了架

**Comment by Born-alone** [comment]
> 我认为是没将本库写到隐私条款中，但通过本库调用了系统oaid的获取方法，所以被oppo定义为静默了。

隐私协议里面加了的

**Comment by sophuron** [comment]
> > 我认为是没将本库写到隐私条款中，但通过本库调用了系统oaid的获取方法，所以被oppo定义为静默了。
> 
> 隐私协议里面加了的

会不会是使用场景的问题：
比如欢迎页面有去请求广告，要用到oaid，但没有在隐私条款中写明本库调用时机及目的。
或者是你的欢迎页面什么都没做，只是提前通过本库获取了oaid。

**Comment by Born-alone** [comment]
> > > 我认为是没将本库写到隐私条款中，但通过本库调用了系统oaid的获取方法，所以被oppo定义为静默了。
> > 
> > 
> > 隐私协议里面加了的
> 
> 会不会是使用场景的问题： 比如欢迎页面有去请求广告，要用到oaid，但没有在隐私条款中写明本库调用时机及目的。 或者是你的欢迎页面什么都没做，只是提前通过本库获取了oaid。

**Comment by Born-alone** [comment]
> > > 我认为是没将本库写到隐私条款中，但通过本库调用了系统oaid的获取方法，所以被oppo定义为静默了。
> > 
> > 
> > 隐私协议里面加了的
> 
> 会不会是使用场景的问题： 比如欢迎页面有去请求广告，要用到oaid，但没有在隐私条款中写明本库调用时机及目的。 或者是你的欢迎页面什么都没做，只是提前通过本库获取了oaid。

我这边只有应用安装后首次打开app且用户同意隐私协议后 才会调用sdk的方法获取oaid 不管回调获取成功失败 都会存储到本地 后续都从本地获取 OPPO那边提供的堆栈信息就是一打开app就调用了库中的方法

**Comment by daquanzheng** [comment]
> 我们的产品现在也遇到了这个问题 OPPO和荣耀都上不了架 ![1726302965901](https://private-user-images.githubusercontent.com/22470202/367501631-20dbd40e-7bdc-4543-8fd6-8706d9118794.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMTIxMjAsIm5iZiI6MTcyNjMxMTgyMCwicGF0aCI6Ii8yMjQ3MDIwMi8zNjc1MDE2MzEtMjBkYmQ0MGUtN2JkYy00NTQzLThmZDYtODcwNmQ5MTE4Nzk0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDExMDM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmZDA5ZjhiZjA0ZmEyOTY1ZjMxYWIzODIwMGM4MjBmNzIxZDZiM2EzNzQ3MmYwZmE2ZjY0ZDY1MWJjMzkxNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9z5CfTyG_JozgKBCrk0pX7vwhy5MQQuYw0BcEF5LHYc)

目前已解决了，之前按照步骤调用了DeviceIdentifier.register()这个方法，现在去看这个方法获取OAID可以不调用，去掉这个方法之后oppo和荣耀的就审核通过了.

**Comment by GuoLiangjun123** [comment]
> > 我们的产品现在也遇到了这个问题 OPPO和荣耀都上不了架 ![1726302965901](https://private-user-images.githubusercontent.com/22470202/367501631-20dbd40e-7bdc-4543-8fd6-8706d9118794.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMTIxMjAsIm5iZiI6MTcyNjMxMTgyMCwicGF0aCI6Ii8yMjQ3MDIwMi8zNjc1MDE2MzEtMjBkYmQ0MGUtN2JkYy00NTQzLThmZDYtODcwNmQ5MTE4Nzk0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDExMDM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmZDA5ZjhiZjA0ZmEyOTY1ZjMxYWIzODIwMGM4MjBmNzIxZDZiM2EzNzQ3MmYwZmE2ZjY0ZDY1MWJjMzkxNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9z5CfTyG_JozgKBCrk0pX7vwhy5MQQuYw0BcEF5LHYc)
> 
> 目前已解决了，之前按照步骤调用了DeviceIdentifier.register()这个方法，现在去看这个方法获取OAID可以不调用，去掉这个方法之后oppo和荣耀的就审核通过了.

你去掉了DeviceIdentifier.register()过后，可以获取到oaid吗？

**Comment by daquanzheng** [comment]
> > > 我们的产品现在也遇到了这个问题 OPPO和荣耀都上不了架 ![1726302965901](https://private-user-images.githubusercontent.com/22470202/367501631-20dbd40e-7bdc-4543-8fd6-8706d9118794.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMTIxMjAsIm5iZiI6MTcyNjMxMTgyMCwicGF0aCI6Ii8yMjQ3MDIwMi8zNjc1MDE2MzEtMjBkYmQ0MGUtN2JkYy00NTQzLThmZDYtODcwNmQ5MTE4Nzk0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDExMDM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmZDA5ZjhiZjA0ZmEyOTY1ZjMxYWIzODIwMGM4MjBmNzIxZDZiM2EzNzQ3MmYwZmE2ZjY0ZDY1MWJjMzkxNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9z5CfTyG_JozgKBCrk0pX7vwhy5MQQuYw0BcEF5LHYc)
> > 
> > 
> > 目前已解决了，之前按照步骤调用了DeviceIdentifier.register()这个方法，现在去看这个方法获取OAID可以不调用，去掉这个方法之后oppo和荣耀的就审核通过了.
> 
> 你去掉了DeviceIdentifier.register()过后，可以获取到oaid吗？

现在只需要通过异步方式获取就行了，绝大部分手机没问题的，DeviceIdentifier.register()这个方法你看看文档 是可选的 不使用getClientId()就行了。我之前也没用过这个方法获取OAID
